### PR TITLE
Added sGoToBall skill

### PR DESCRIPTION
**Pull request by sipah00**
Some constants Yet  to be  defined.

### CODE REVIEW

**Comment by MayankB11** [comment]
@sipah00 In line number 12 and 20, is the obstacle() defined ? Also, the python skills would not return the commands. They will directly execute then. So, no return keyword is required.

**Comment by sipah00** [comment]
@MayankB11 ,I think obstacle class should  be defined globally somewhere(like Vector2D)and use in this skill.Give me some Idea..

**Comment by MayankB11** [comment]
There is no need to define that. You can directly take a variable say 'o' and add the obstacle details and then add it to a **list** of obstacles.

**Comment by sipah00** [comment]
we have to send the list of obstacles to pathplanner . so i think we cant define it locally .

**Pull request closed without merging**
